#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: my-ubuntu-server
    username: myuser
    password: "$6$MeDi2NdTh5upzTNI$NupTi.G1MXfZtKB5yLmbGKAq3ZC.8FM48sLN3Rysg7wVi5CTQCz6japdxNybPM5zfBJUTQj3aaFwZlA8npOmU." # Replace with your hashed password
  keyboard:
    layout: us
    variant: ''
  locale: en_US.UTF-8
  storage:
    config:
      - { type: disk, id: nvme0n1, ptable: gpt, wipe: superblock-recursive, preserve: false, name: '', grub_device: true, 
          serial: n/a, path: /dev/nvme0n1 }
      - { type: partition, id: nvme0n1p1, device: nvme0n1, size: 512M, wipe: superblock, flag: boot, number: 1 }
      - { type: partition, id: nvme0n1p2, device: nvme0n1, size: 1024M, wipe: superblock, flag: none, number: 2 }
      - { type: partition, id: nvme0n1p3, device: nvme0n1, size: -1, wipe: superblock, flag: none, number: 3 }
      - { type: format, id: nvme0n1p1-format, fstype: fat32, volume: nvme0n1p1 }
      - { type: mount, id: nvme0n1p1-mount, device: nvme0n1p1, path: /boot/efi }
      - { type: format, id: nvme0n1p2-format, fstype: ext4, volume: nvme0n1p2 }
      - { type: mount, id: nvme0n1p2-mount, device: nvme0n1p2, path: /boot }
      - { type: luks, id: luks-nvme0n1p3, key: "mypassword", device: nvme0n1p3 } # Set the encryption password
      - { type: lvmpv, id: pv-nvme0n1p3, device: luks-nvme0n1p3 }
      - { type: lvmvolgroup, id: vg0, name: vg0, devices: [pv-nvme0n1p3] }
      - { type: lvmlv, id: lv-root, name: root, volgroup: vg0, size: 50%FREE }
      - { type: lvmlv, id: lv-home, name: home, volgroup: vg0, size: 50%FREE }
      - { type: format, id: lv-root-format, fstype: ext4, volume: lv-root }
      - { type: mount, id: lv-root-mount, device: lv-root, path: / }
      - { type: format, id: lv-home-format, fstype: ext4, volume: lv-home }
      - { type: mount, id: lv-home-mount, device: lv-home, path: /home }
  packages:
    - vim
    - htop
    - curl
  user-data:
    apt:
      preserve_sources_list: false
      disable_suites: []
    package_update: true
    package_upgrade: true
    runcmd:
      - apt-get -y autoremove
      - apt-get -y clean
      - echo "Setup complete" > /etc/motd
  grub:
    install_devices: ['/dev/nvme0n1']
