#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu24-img
    username: sysadmin
    password: $6$MeDi2NdTh5upzTNI$NupTi.G1MXfZtKB5yLmbGKAq3ZC.8FM48sLN3Rysg7wVi5CTQCz6japdxNybPM5zfBJUTQj3aaFwZlA8npOmU.

  storage:
    layout:
      name: lvm
      password: Withckck02
    config:
      - id: disk0
        type: disk
        ptable: gpt
        path: /dev/nvme0n1
        wipe: superblock

        grub_device: true
        device: /dev/nvme0n1

        partitions:
          - type: partition
            id: partition-efi
            size: 2GB
            flag: boot
            number: 1
          - type: partition
            id: partition-lvm
            size: -1
            number: 2

      - id: lvm-group
        type: lvm_volgroup
        name: vg0
        devices:
          - partition-lvm
      
      - id: lvm-root
        type: lvm_partition
        size: 160GB
        name: root
        mount_point: /
      
      - id: lvm-home
        type: lvm_partition
        size: -1
        name: home
        mount_point: /home


