Vagrant.configure("2") do |config|

  config.vm.define "scriptbox" do |scriptbox|
    scriptbox.vm.box = "generic/centos7"
    scriptbox.vm.hostname = "scriptbox"
  end

  config.vm.define "web01" do |web01|
    web01.vm.box = "generic/centos7"
    web01.vm.hostname = "web01"
  end

  config.vm.define "web02" do |web02|
    web02.vm.box = "generic/centos7"
    web02.vm.hostname = "web02"
  end

  config.vm.define "web03" do |web03|
    web03.vm.box = "generic/ubuntu2004"
    web03.vm.hostname = "web03"
  end

end

